// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rookie.AssetManagement.DataAccessor.Data;

namespace Rookie.AssetManagement.DataAccessor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220419181413_seed data Asset and Assignment")]
    partial class seeddataAssetandAssignment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            Code = "LA000001",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 458, DateTimeKind.Local).AddTicks(7261),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(4558),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 1,
                            Code = "LA000002",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8299),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8330),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 1,
                            Code = "LA000003",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8337),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8341),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 1,
                            Code = "LA000004",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8345),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8348),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 1,
                            Code = "LA000005",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8352),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8354),
                            Location = 2,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 2,
                            Code = "MO000001",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8359),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8361),
                            Location = 1,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryID = 2,
                            Code = "MO000002",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8365),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8369),
                            Location = 1,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryID = 2,
                            Code = "MO000003",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8374),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8376),
                            Location = 1,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryID = 2,
                            Code = "MO000004",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8380),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8383),
                            Location = 2,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryID = 2,
                            Code = "MO000005",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8387),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8391),
                            Location = 2,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryID = 2,
                            Code = "MO000006",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8396),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8399),
                            Location = 2,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryID = 3,
                            Code = "PC000001",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8403),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8406),
                            Location = 1,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryID = 3,
                            Code = "PC000002",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8409),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8412),
                            Location = 1,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryID = 3,
                            Code = "PC000003",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8416),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8419),
                            Location = 2,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryID = 3,
                            Code = "PC000004",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8423),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8426),
                            Location = 2,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryID = 1,
                            Code = "LA000006",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8430),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8433),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryID = 1,
                            Code = "LA000007",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8438),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8441),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryID = 1,
                            Code = "LA000008",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8445),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8448),
                            Location = 1,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 3
                        },
                        new
                        {
                            Id = 19,
                            CategoryID = 1,
                            Code = "LA000009",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8452),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8454),
                            Location = 2,
                            Name = "Laptop HP Pro Book 450 G1",
                            Specification = "Specification of Laptop",
                            State = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryID = 2,
                            Code = "MO000007",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8458),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8461),
                            Location = 1,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 3
                        },
                        new
                        {
                            Id = 21,
                            CategoryID = 2,
                            Code = "MO000008",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8465),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8468),
                            Location = 2,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 2
                        },
                        new
                        {
                            Id = 22,
                            CategoryID = 2,
                            Code = "MO000009",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8472),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8475),
                            Location = 2,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 2
                        },
                        new
                        {
                            Id = 23,
                            CategoryID = 2,
                            Code = "MO000010",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8478),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8481),
                            Location = 1,
                            Name = "Monitor Dell UltraSharp",
                            Specification = "Specification of Monitor",
                            State = 3
                        },
                        new
                        {
                            Id = 24,
                            CategoryID = 3,
                            Code = "PC000005",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8486),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8489),
                            Location = 1,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 3
                        },
                        new
                        {
                            Id = 25,
                            CategoryID = 3,
                            Code = "PC000006",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8493),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8495),
                            Location = 1,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 3
                        },
                        new
                        {
                            Id = 26,
                            CategoryID = 3,
                            Code = "PC000007",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8499),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8502),
                            Location = 2,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 3
                        },
                        new
                        {
                            Id = 27,
                            CategoryID = 3,
                            Code = "PC000008",
                            InstallDate = new DateTime(2023, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8507),
                            IsDeleted = false,
                            LastUpdate = new DateTime(2022, 4, 20, 1, 14, 12, 460, DateTimeKind.Local).AddTicks(8509),
                            Location = 2,
                            Name = "Personal Computer",
                            Specification = "Specification of PC",
                            State = 2
                        });
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop",
                            ShortName = "LA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitor",
                            ShortName = "MO"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Personal Computer",
                            ShortName = "PC"
                        });
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetID")
                        .HasColumnType("int");

                    b.Property<int?>("AssignByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignToID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetID");

                    b.HasIndex("AssignByID");

                    b.HasIndex("AssignToID");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetID = 16,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 463, DateTimeKind.Local).AddTicks(7613),
                            AssignToID = 14,
                            IsDelete = false,
                            Location = 1,
                            Note = "Assign asset to this staff.",
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetID = 17,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3070),
                            AssignToID = 15,
                            IsDelete = false,
                            Location = 1,
                            Note = "Assign asset to this staff.",
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            AssetID = 18,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3094),
                            AssignToID = 16,
                            IsDelete = false,
                            Location = 1,
                            Note = "Assign asset to this staff.",
                            State = 2
                        },
                        new
                        {
                            Id = 4,
                            AssetID = 19,
                            AssignByID = 6,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3106),
                            AssignToID = 8,
                            IsDelete = false,
                            Location = 2,
                            Note = "Assign asset to this staff.",
                            State = 1
                        },
                        new
                        {
                            Id = 5,
                            AssetID = 20,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3112),
                            AssignToID = 17,
                            IsDelete = false,
                            Location = 1,
                            Note = "Assign asset to this staff.",
                            State = 2
                        },
                        new
                        {
                            Id = 6,
                            AssetID = 21,
                            AssignByID = 6,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3119),
                            AssignToID = 9,
                            IsDelete = false,
                            Location = 2,
                            Note = "Assign asset to this staff.",
                            State = 1
                        },
                        new
                        {
                            Id = 7,
                            AssetID = 22,
                            AssignByID = 6,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3125),
                            AssignToID = 10,
                            IsDelete = false,
                            Location = 2,
                            Note = "Assign asset to this staff.",
                            State = 1
                        },
                        new
                        {
                            Id = 8,
                            AssetID = 23,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3131),
                            AssignToID = 14,
                            IsDelete = false,
                            Location = 1,
                            Note = "Assign asset to this staff.",
                            State = 2
                        },
                        new
                        {
                            Id = 9,
                            AssetID = 24,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3137),
                            AssignToID = 14,
                            IsDelete = false,
                            Location = 1,
                            Note = "Assign asset to this staff.",
                            State = 2
                        },
                        new
                        {
                            Id = 10,
                            AssetID = 25,
                            AssignByID = 6,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3146),
                            AssignToID = 11,
                            IsDelete = false,
                            Location = 2,
                            Note = "Assign asset to this staff.",
                            State = 2
                        },
                        new
                        {
                            Id = 11,
                            AssetID = 26,
                            AssignByID = 6,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3153),
                            AssignToID = 12,
                            IsDelete = false,
                            Location = 2,
                            Note = "Assign asset to this staff.",
                            State = 2
                        },
                        new
                        {
                            Id = 12,
                            AssetID = 27,
                            AssignByID = 4,
                            AssignDate = new DateTime(2022, 4, 20, 1, 14, 12, 464, DateTimeKind.Local).AddTicks(3158),
                            AssignToID = 12,
                            IsDelete = false,
                            Location = 2,
                            Note = "Assign asset to this staff.",
                            State = 1
                        });
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("FirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Asset", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.Assignment", b =>
                {
                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", "AssignBy")
                        .WithMany()
                        .HasForeignKey("AssignByID");

                    b.HasOne("Rookie.AssetManagement.DataAccessor.Entities.User", "AssignTo")
                        .WithMany()
                        .HasForeignKey("AssignToID");

                    b.Navigation("Asset");

                    b.Navigation("AssignBy");

                    b.Navigation("AssignTo");
                });

            modelBuilder.Entity("Rookie.AssetManagement.DataAccessor.Entities.AssetCategory", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
